### ISSUE TITLE
Accessibility consultant & Community connector: create and edit

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#411]
- [x] #271
- [x] #274

**Comment by cherylhjli** [comment]
Creating profile:
Now there are only 4 steps: About you, experiences, interests, and communications & meeting preferences*. We decided to move access needs out to its separate page. Communication and meeting preferences is also a separate page, but can be changed here. Same with languages.

* I'm not set on "communication and meeting preferences" because it's quite a mouthful. I'm not 100% sure about "engagement preferences" either because we use engagements to specifically refer to the event under a project. And they're entering this info for meeting and communicating with the FRO. Open to suggestions! We could also leave it for Aruna.

About you: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1725%3A47435
Experiences: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1725%3A47554
Interests: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1725%3A47515
Communication & meeting preferences: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1758%3A48266

View profile
- Previewing a draft: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A16052
- Successfully published: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A36401
- Experiences: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A36619
- Interests: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A36832
- Comm & meeting preferences: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A37222
- Add photo: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A16117
- Reposition photo: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A16123
